# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: valhallalinux
description: Immutable Linux distro based on Bluefin-DX, featuring COSMIC and Tuxedo Tools.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/ into your image's root folder.

  - type: dnf
    repos:
      copr:
        - darrencocco/tuxedo-control-center
    install:
      packages:
        # --- TUXEDO TOOLS ---
        - tuxedo-control-center
        - tuxedo-drivers
        
        # --- COSMIC DESKTOP ---
        - cosmic-desktop
        
        # --- TERMINAL & TOOLS ---
        - foot
        - micro
        - fish
        - fastfetch
        - git
        - brightnessctl

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished 
        scope: system
        install: 
        # we love app images
          - it.mijorus.gearlever
      - scope: user 

  - type: os-release
    properties:
      ID: valhallalinux
      ID_Like: fedora
      NAME: Valhalla Linux
      PRETTY_NAME: Valhalla Linux (Bluefin-DX Based)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
