---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: valhalla-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship

        # 1) Virtual Machine Manager & Dependencies
        - virt-manager
        - qemu-kvm
        - libvirt
        - edk2-ovmf

        # 2) Multimedia Codecs & Nautilus Thumbnail Vorschau
        - ffmpeg
        - gstreamer1-plugin-libav
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-ugly
        - ffmpegthumbnailer
        - totem-video-thumbnailer
        - gdk-pixbuf2-raw-thumbnailer # Korrigierter Paketname
        - gnome-epub-thumbnailer

        # 3) KDE Texteditor
        - kate

        # 4) GNOME Extensions Tools
        - gnome-extensions-app
        - gnome-browser-connector

        # 5) Container & Dev Tools
        - distrobox
        - just
        - podman-compose
        - podman-docker
        - neovim

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - org.gnome.Loupe
          - com.visualstudio.code # VS Code sauber über Flathub
      - scope: user 

  - type: signing
